# Fully customizable popup bar.
# If you have any tag requests please DM them to Dapro#3132 on Discord.
# DM Dapro#3132 if you need any help.


# Edit how often the popup bar is updated. (In seconds, no more that 5 recomended. If using coordinates, 1 second recomended)
update-interval: 5

# Utils

# {X} - Player's X coordinate.
# {Y} - Player's Y coordinate.
# {Z} - Player's Z coordinate.
# {ONLINE} - Current online players.
# {MAX_ONLINE} - Maxumim possible online players.
# {PLAYER_ONLINE_TIME} - Player's total online time.
# {HEALTH} - Player's current health. 
# {MAX_HEALTH} - Player's maximum health.
# {MONEY} - Player's money.


# KDR Plugin

# {KILLS} - Player's total kills.
# {DEATHS} - Player's total deaths.
# {KILL_DEATH_RATE} - Player's kill death rate.


# Faction Plugin

# {FACTION} - Faction the player is in.
# {FACTION_POWER} - The power of the faction the player is in.


# RedSkyBlock Plugin

# {ISLAND_NAME} - The player's island name.
# {ISLAND_SIZE} - The player's island size.
# {ISLAND_RANK} - The player's island rank.
# {ISLAND_VALUE} - The player's island value.

# If you have any tag requests please DM them to Dapro#3132 on Disocord.


# Edit the popup bar format. Use '§' for colors and the tags above for addons. (Only works if multi world is set to false).
popup-format: '§e{X}, {Y}, {Z} | {ONLINE}/{MAX_ONLINE} players online!'

# Allows you to have different popup bars per world.
multi-world: false

# Edit the popup bar format per world. Use '§' for colors and the tags above for addons. 
# Only works if multi world is set to true.
# Example: world: '§e{X}, {Y}, {Z} | {ONLINE}/{MAX_ONLINE} players online!'

worlds: 
 - world:
   - '§e{X}, {Y}, {Z} | {ONLINE}/{MAX_ONLINE} players online!'
 - world2:
   - 'This is a popup bar!'
