# Fully customizable popup bar.
# DM Dapro#3132 if you need any help.

# Imperial Network
# Ip: play-imperialpe.xyz
# Port: 19132
# Discord: https://discord.gg/GdtwwuG
# Website: imperialpe.xyz


# Edit how often the popup bar is updated. (In seconds, no more that 5 recomended. If using coordinates, 1 second recomended)
update-interval:


# {X} - Player's X coordinate.
# {Y} - Player's Y coordinate.
# {Z} - Player's Z coordinate.
# {ONLINE} - Current online players.
# {MAX_ONLINE} - Maxumim possible online players.
# {TIME} - Current time. (mm/dd/yyyy).
# {ONLINE_TIME} - Online time of the server.
# {PLAYER_ONLINE_TIME} - Player's total online time.
# {HEALTH} - Player's current health. 
# {MAX_HEALTH} - Player's maximum health.
# {MONEY} - Player's money.
# {KILLS} - Player's total kills.
# {DEATHS} - Player's total deaths.
# {KILL_DEATH_RATE} - Player's kill death rate.
# {} - 
# {} - 
# {} - 
# {} - 
